file_format: "1"
id: daedalus
name: Daedalus
type: shield
url: https://github.com/Perseus333/daedalus-kbd
requires: [pro_micro]
exposes: [i2c_trackpad]
features:
  - keys
  - display
  - encoder
siblings:
  - daedalus_left
  - daedalus_right