name: Build ZMK Config

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/zmk-prebuilt:latest

    steps:
      - name: Checkout user config
        uses: actions/checkout@v4

      - name: Set up ZMK app directory
        run: |
          mkdir -p zmk-config/config
          cp -r config/* zmk-config/config/
          cp -r zmk/* zmk-config/
          cd zmk-config
          west init -l .
          west update
          west zephyr-export

      - name: Build firmware
        run: |
          cd zmk-config
          west build -s app -d build/left -b nice_nano_v2 -- -DSHIELD=your_left_shield
          west build -s app -d build/right -b nice_nano_v2 -- -DSHIELD=your_right_shield

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            zmk-config/build/left/zephyr/zmk.uf2
            zmk-config/build/right/zephyr/zmk.uf2
